### ISSUE TITLE
Configuring .env

### ISSUE THREAD

**Issue by smooJitter** [danielweinmann/TemAcucar#1]
Could you explain more about how run this app? I made three copies of the .env.sample files and change the names accordingly.  When I try running the app, the error messages seemed to indicate problems with the .env files.   I open the files and noticed several API keys.  Are those required to run the app?

**Comment by danielweinmann** [comment]
Hi @smooJitter! Just out of curiosity, what is your goal with running this app?

The app is still in (very active, before alpha) development, so you might run into bugs and see big rewrites while following it.

That said, what command are you using to run the app?

**Comment by smooJitter** [comment]
I am sort of a newbie (meteor+mantra+react-native+mongodb).  I was initial drawn to the app for two reasons.  You router react-native-router-flux and because have implemented react-native-maps. With the exception of Redux, I see you are implementing other react-native packages that I've decided to adopt. Since there was no screen shots, I was hoping to see how it all came together, particular your maps solution. I'm still trying to determine if I should go with react-native-maps.  I was originally leaning towards Mapbox. It's been a while since I last tried to run it but I believe I followed the instructions regarding the .env files, opened the .xproj file and ran the iOS simulator via xcode.  Note, I am not familiar with working with .env so I didn't have much to bring to debugging.  Does that help?

**Comment by danielweinmann** [comment]
The only way right now to run the app is through `bin/run-ios`. That's because we have to generate Info.plist and AppDelegate.m from a template in order to inject the config vars for the selected environment. It's a hack I found to be really useful while react native does not fully support config vars. You can check out the code in the bin/folder to see what I am doing ;)

To be able to see the maps in action you will have to at least configure `API_URL` and `GOOGLE_MAPS_API_KEY` and have the api running locally from https://github.com/danielweinmann/tem-acucar-api ;) I don't know if it's worth the effort just to see the maps, but let me know if you need anything!
